wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: GPT2
dataset:
  desc: null
  value: SAMSUM
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708268735.316355
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 2
      - 16
      - 23
      4: 3.11.4
      5: 0.16.3
      6: 4.37.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
